"""
Tests for vol_surface.py - SVI fitting, SABR, surface construction.
"""

import pytest
import numpy as np
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from vol_surface import (
    svi_raw, svi_implied_vol, fit_svi_slice, sabr_implied_vol,
    fit_sabr, VolSurface, term_structure
)


class TestSVI:
    def test_svi_positive_variance(self):
        """SVI total variance must be positive."""
        k = np.linspace(-0.5, 0.5, 100)
        w = svi_raw(k, a=0.04, b=0.1, rho=-0.3, m=0.0, sigma=0.2)
        assert np.all(w > 0)

    def test_svi_symmetric_no_skew(self):
        """SVI with rho=0 is symmetric around m."""
        k = np.array([-0.2, -0.1, 0.0, 0.1, 0.2])
        w = svi_raw(k, a=0.04, b=0.1, rho=0.0, m=0.0, sigma=0.2)
        assert abs(w[0] - w[4]) < 1e-10
        assert abs(w[1] - w[3]) < 1e-10

    def test_svi_smile_minimum_at_m(self):
        """SVI minimum total variance is at k=m when rho=0."""
        k = np.linspace(-1, 1, 1000)
        w = svi_raw(k, a=0.04, b=0.1, rho=0.0, m=0.1, sigma=0.2)
        min_idx = np.argmin(w)
        assert abs(k[min_idx] - 0.1) < 0.01

    def test_svi_implied_vol_positive(self):
        k = np.linspace(-0.3, 0.3, 50)
        iv = svi_implied_vol(k, T=0.5, a=0.04, b=0.1, rho=-0.3, m=0.0, sigma=0.2)
        assert np.all(iv > 0)

    def test_svi_fit_recovers_params(self):
        """Fit SVI to data generated by known params: recover params well."""
        k = np.linspace(-0.3, 0.3, 20)
        T = 0.5
        F = 100.0
        true_params = (0.04, 0.1, -0.3, 0.0, 0.2)
        strikes = F * np.exp(k)
        iv_true = svi_implied_vol(k, T, *true_params)

        params_fit, rmse = fit_svi_slice(strikes, iv_true, F, T)
        iv_fit = svi_implied_vol(k, T, *params_fit)
        assert rmse < 0.005
        assert np.max(np.abs(iv_fit - iv_true)) < 0.005

    def test_svi_fit_real_smile(self):
        """Fit SVI to a realistic market smile with negative skew."""
        F = 5800.0
        k = np.linspace(-0.2, 0.1, 15)
        strikes = F * np.exp(k)
        T = 0.25
        # Realistic smile: ATM=18%, OTM puts have higher vol, OTM calls lower
        iv = 0.18 + (-0.15) * k + 0.08 * k ** 2
        iv = np.maximum(iv, 0.05)

        params, rmse = fit_svi_slice(strikes, iv, F, T)
        assert rmse < 0.02  # Reasonable fit


class TestSABR:
    def test_atm_sabr(self):
        """SABR ATM formula returns positive vol."""
        vol = sabr_implied_vol(F=100, K=100, T=0.5, alpha=0.3, beta=0.5, rho=-0.3, nu=0.4)
        assert vol > 0

    def test_sabr_smile_shape(self):
        """SABR produces a smile (higher vols for OTM options)."""
        F = 100
        T = 0.5
        alpha, beta, rho, nu = 0.3, 0.5, -0.3, 0.4
        atm = sabr_implied_vol(F, F, T, alpha, beta, rho, nu)
        otm_call = sabr_implied_vol(F, F * 1.1, T, alpha, beta, rho, nu)
        otm_put = sabr_implied_vol(F, F * 0.9, T, alpha, beta, rho, nu)
        # With negative rho, put skew should be higher than ATM
        assert otm_put > atm

    def test_sabr_fit_recovers_smile(self):
        """SABR fit should recover input smile accurately."""
        F, T = 100.0, 0.5
        alpha, beta, rho, nu = 0.3, 0.5, -0.3, 0.4
        strikes = np.array([85, 90, 95, 100, 105, 110, 115], dtype=float)
        ivols = np.array([sabr_implied_vol(F, K, T, alpha, beta, rho, nu) for K in strikes])

        params_fit, rmse = fit_sabr(strikes, ivols, F, T, beta=beta)
        assert rmse < 0.01


class TestVolSurface:
    def test_synthetic_surface_built(self):
        surf = VolSurface(S=580, r=0.05, q=0.015)
        surf.build_synthetic(n_strikes=20, n_expiries=10)
        assert surf.surface_grid is not None
        assert surf.surface_grid.shape == (20, 10)

    def test_surface_vols_positive(self):
        surf = VolSurface(S=580, r=0.05, q=0.015)
        surf.build_synthetic(n_strikes=30, n_expiries=15)
        assert np.all(surf.surface_grid > 0)

    def test_get_vol_interpolation(self):
        surf = VolSurface(S=100, r=0.05)
        surf.build_synthetic(K_range=(0.8, 1.2), T_range=(0.1, 1.0),
                             n_strikes=20, n_expiries=10)
        vol = surf.get_vol(K=100, T=0.5)
        assert 0.05 < vol < 1.0

    def test_surface_render_speed(self):
        """Surface build time <5s."""
        import time
        surf = VolSurface(S=5800, r=0.05)
        start = time.time()
        surf.build_synthetic(n_strikes=50, n_expiries=20)
        elapsed = time.time() - start
        assert elapsed < 5.0, f"Surface took {elapsed:.2f}s (>5s limit)"

    def test_skew_direction(self):
        """Negative skew: OTM puts have higher vol than OTM calls."""
        surf = VolSurface(S=100, r=0.05)
        surf.build_synthetic(K_range=(0.8, 1.2), T_range=(0.1, 1.0),
                             n_strikes=30, n_expiries=10, skew=-0.15)
        # Get vol for OTM put (K=85) and OTM call (K=115) at T=0.5
        vol_put = surf.get_vol(85, 0.5)
        vol_call = surf.get_vol(115, 0.5)
        assert vol_put > vol_call


class TestVolSurfaceFromChain:
    def test_build_from_synthetic_chain(self):
        """Build surface from synthetic chain data."""
        from data import _synthetic_chain
        chain = _synthetic_chain(S=100, r=0.05, q=0.0, atm_vol=0.20)
        surf = VolSurface(S=100, r=0.05, q=0.0)
        surf.build_from_chain(chain, option_type="call")
        # May or may not build depending on chain quality
        assert surf is not None

    def test_get_vol_no_surface_returns_default(self):
        """get_vol without built surface returns default 0.20."""
        surf = VolSurface(S=100, r=0.05)
        vol = surf.get_vol(K=100, T=0.5)
        assert vol == 0.20

    def test_get_vol_single_slice(self):
        """get_vol with minimal surface (single expiry, falls back to nearest)."""
        surf = VolSurface(S=100, r=0.05)
        surf.build_synthetic(K_range=(0.9, 1.1), T_range=(0.2, 0.8),
                             n_strikes=5, n_expiries=5)
        vol = surf.get_vol(100, 0.5)
        assert 0.05 < vol < 1.0

    def test_local_vol_dupire(self):
        """Dupire local vol is positive and finite."""
        surf = VolSurface(S=100, r=0.05)
        surf.build_synthetic(K_range=(0.8, 1.2), T_range=(0.1, 1.0),
                             n_strikes=25, n_expiries=12)
        lv = surf.local_vol_dupire(K=100, T=0.5)
        assert np.isfinite(lv)
        assert lv > 0

    def test_local_vol_no_surface_fallback(self):
        """local_vol returns positive finite value when no surface built."""
        surf = VolSurface(S=100, r=0.05)
        lv = surf.local_vol_dupire(K=100, T=0.5)
        assert np.isfinite(lv)
        assert lv > 0


class TestTermStructure:
    def test_term_structure_shape(self):
        T = np.array([0.1, 0.25, 0.5, 1.0, 2.0])
        vols = np.array([0.25, 0.22, 0.20, 0.19, 0.18])
        ts = term_structure(T, vols)
        assert "forward_vols" in ts
        assert len(ts["forward_vols"]) == 4

    def test_calendar_arb_free_upward(self):
        """Upward sloping variance curve is calendar arb free."""
        T = np.array([0.1, 0.25, 0.5, 1.0])
        vols = np.array([0.15, 0.17, 0.18, 0.19])
        ts = term_structure(T, vols)
        assert ts["calendar_arb_free"]

    def test_forward_vol_positive(self):
        T = np.array([0.25, 0.5, 1.0])
        vols = np.array([0.20, 0.19, 0.18])
        ts = term_structure(T, vols)
        assert np.all(ts["forward_vols"] >= 0)
